const NAVIGATE_TYPES = [
  "lead",
  "contact",
  "accounts",
  "user",
  "quotation",
  "opportunity",
  "task",
  "event",
];

const STANDARD_FIELD_LABELS = {
  lead: [
    "Owner",
    "Name *",
    "Name",
    "Status",
    "Source",
    "Lead Type",
    "Organization Name *",
    "Details",
    "Contact Name",
    "Email Id",
    "Personal Contact No.",
    "Whatsapp No.",
    "Official No.",
    "Created On",
    "Last Modified On",
    "Country",
    "State",
    "City",
    "Zip / Postal Code",
    "Address",
    "Zip",
    "Zip Code",
    "Postal Code",
  ],
  accounts: [
    "Owner",
    "Account Name *",
    "Account Name",
    "Name",
    "Account",
    "Owner *",
    "Type *",
    "Parent Account",
    "Website",
    "Contact No *",
    "Contact",
    "Industry *",
    "Employee *",
    "Description",
    "Created On",
    "Last Modified On",
    "Billing Country *",
    "Billing State *",
    "Billing City",
    "Zip / Postal Code *",
    "Billing Address",
    "Make Shipping Address same as Billing Address",
    "Shipping Country *",
    "Shipping State *",
    "Shipping City",
    "Shipping Address",
    "Zip Code",
    "Postal Code",
  ],
  contact: [
    "Owner *",
    "Owner",
    "Account Name *",
    "Account Name",
    "Name",
    "Saluation",
    "First Name *",
    "First Name",
    "Middle Name",
    "Last Name *",
    "Last Name",
    "Designation",
    "Contact No*",
    "Contact No",
    "Email",
    "Email Id",
    "Fax",
    "Created On",
    "Last Modified On",
    "Mailing Country",
    "Mailing State",
    "Mailing City",
    "Zip / Postal Code",
    "Mailing Full Address",
  ],
  user: [
    "User Profile *",
    "Name *",
    "Last Name *",
    "User Profile",
    "Name",
    "Last Name",
    "Contact No",
    "Email *",
    "Email",
    "Division",
    "Department",
    "Designation",
    "Report/Assign To *",
    "Report/Assign To",
    "Assign To",
    "Report To",
    "Optional Detail",
    "Address",
    "Country",
    "State",
    "City",
    "Zip / Postal Code",
    "Aadhar Card",
    "Upload Aadhar Card",
    "Pan Card",
    "GST Number",
    "Organisation",
    "Upload Pan Card",
    "Driving License *",
    "Driving License",
    "Upload Driving License",
    "Bank Name",
    "Account Holder Name",
    "Account Number",
    "Bank IFSC Code",
    "Branch",
    "Bank Cancelled Cheque",
  ],
  opportunity: [
    "Opportunity Name *",
    "Opportunity Name",
    "Name",
    "Account Name *",
    "Account Name",
    "Contact Name *",
    "Contact Name",
    "Close date *",
    "Stage *",
    "Owner *",
    "Type *",
    "Close date",
    "Stage",
    "Owner",
    "Type",
    "Amount/Value *",
    "Lead Source *",
    "Description",
    "Amount/Value",
    "Lead Source",
    "Product of Services",
    "Quantity",
    "Price",
    "Created On",
    "Last Modified On",
  ],
  quotation: [],
  task: [],
  event: [],
};

const dedupeLabels = (labels) => [...new Set(labels)];

const getStandardFieldLabels = (navigateType) =>
  dedupeLabels(STANDARD_FIELD_LABELS[navigateType] || []);

const getStandardFields = (navigateType) =>
  getStandardFieldLabels(navigateType).map((field_lable, index) => ({
    field_lable,
    is_standard: true,
    field_type: "standard",
    field_order: index + 1,
  }));

module.exports = {
  NAVIGATE_TYPES,
  STANDARD_FIELD_LABELS,
  getStandardFieldLabels,
  getStandardFields,
};
